name: samrental
description: Car renting mobile application

publish_to: 'none' 

version: 0.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.3
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.9
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/
    - assets/fonts/
    - assets/icons/
    - assets/images/

  fonts:
    - family: "SF Pro Display"
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.OTF
        - asset: assets/fonts/SF-Pro-Display-Medium.OTF
        - asset: assets/fonts/SF-Pro-Display-Thin-Italic.OTF
        - asset: assets/fonts/SF-Pro-Display-Black-Italic.OTF
        - asset: assets/fonts/SF-Pro-Display-Bold.OTF
        - asset: assets/fonts/SF-Pro-Display-Heavy-Italic.OTF
        - asset: assets/fonts/SF-Pro-Display-Light-Italic.OTF
        - asset: assets/fonts/SF-Pro-Display-SemiBold-Italic.OTF
  
