// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtfvGr7FSvPceToWPKjg6NjsuOggdA6R4',
    appId: '1:103830699007:web:29bc4f33f37394b3cc85ca',
    messagingSenderId: '103830699007',
    projectId: 'samrental-678ee',
    authDomain: 'samrental-678ee.firebaseapp.com',
    storageBucket: 'samrental-678ee.appspot.com',
    measurementId: 'G-65YF35Q7WP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAinXZFCiXKzULUq3NOgY9zxVnvx3Kquis',
    appId: '1:103830699007:android:10b30dd2c15bcaf8cc85ca',
    messagingSenderId: '103830699007',
    projectId: 'samrental-678ee',
    storageBucket: 'samrental-678ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJwPR0kJrXsjbyXfefdVJUjFCI9anZzKQ',
    appId: '1:103830699007:ios:13929d19439c2132cc85ca',
    messagingSenderId: '103830699007',
    projectId: 'samrental-678ee',
    storageBucket: 'samrental-678ee.appspot.com',
    iosBundleId: 'org.cdevs.samrental',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJwPR0kJrXsjbyXfefdVJUjFCI9anZzKQ',
    appId: '1:103830699007:ios:a86c157ebf96d0f2cc85ca',
    messagingSenderId: '103830699007',
    projectId: 'samrental-678ee',
    storageBucket: 'samrental-678ee.appspot.com',
    iosBundleId: 'org.cdevs.samrental.RunnerTests',
  );
}
